config/routes.rb
Rails.application.routes.draw do
  
  resources :image_tags
  resources :tags
  resources :images 
 

  resources :users

  resources :users, only: [:new, :create, :index]
  resources :images, only: [:new,:create, :index,:show]
  resources :login, only: [:new, :create]
  delete "logout", to: "login#destroy", as: "log_out"
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ImageDetails.rb
class ImageDetails

    attr_accessor :image
    attr_accessor :tags

    def initialize(image, tags)
        @image = image
        @tags = tags
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_many :image_tags
  has_many :tags, through: :image_tags

  
  #getter
  def tags
    @tags
  end
  
  #setter
  def tags=(value)
    @tags = value
  end

end

app/models/image_similarity.rb
class ImageSimilarity < ApplicationRecord
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
  belongs_to :image
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :image_tags
    has_many :images, through: :image_tags
end

app/models/user.rb
class User < ApplicationRecord
    has_many :images
    has_many :image_tags, through: :images
    has_many :tags, through: :image_tags

    validates :username, uniqueness: { case_sensitive: false }
    validates :password, confirmation: { case_sensitive: true }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
    before_action :fetch_user

    def fetch_user
        @logged_in = logged_in?
        if @logged_in
            @user = User.find(session[:user_id])
        else
            redirect_to new_login_path
        end
    end

    def logged_in?
        !!session[:user_id]
    end


    def log_out_user!
        session.delete(:user_id)
    end 

end

app/controllers/image_tags_controller.rb
class ImageTagsController < ApplicationController
end

app/controllers/images_controller.rb
require_relative '../helpers/images_helper'

class ImagesController < ApplicationController
    skip_before_action :fetch_user, only: [:new,:create, :index, :show]

    #created class variables for respective class in helper module for create and show methods
    @@search_image = ImagesHelper::SearchImages.new
    @@cloudinary = ImagesHelper::CloudinaryAPI.new
    @@create_image = ImagesHelper::CreateUpdateImages.new

    def index
        @user = User.find(session[:user_id])
        @image_for_user = Image.where("user_id = #{session[:user_id]}")
        @image = Image.new
        @logged_in = true
    end

    def new
        @user = User.find(session[:user_id])
        @image = Image.new
    end

    def create
        uploaded_image_details = @@cloudinary.upload(params[:image][:photo])
        @@create_image.create(session[:user_id], params[:image][:title].strip, 
                        uploaded_image_details, params[:image][:tags].split(','));
        redirect_to '/images'
    end

    #shows the image selected in the index page
    def show
        @logged_in = true
        @user = User.find(session[:user_id])
        @image = Image.new
        @image_for_user = @@search_image.search(params, @user.id)
        
        render :index
    end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    skip_before_action :fetch_user, only: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(username: params[:username]) 
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to '/images'
        else
            flash[:message]= "User Not Found"
            redirect_to '/login/new'
        end
    end


    def destroy
        log_out_user!
        redirect_to new_user_path
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :fetch_user, only: [:new,:create]
    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to '/images'
        else
            flash[:errors] = @user.errors
            redirect_to new_user_path
        end
    end


    private

    def user_params
        params.require(:user).permit(:username,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_tags_helper.rb
module ImageTagsHelper
end

app/helpers/images_helper.rb
module ImagesHelper

    class CreateUpdateImages
        
        def create (user_id, title, uploaded_image_details, tags)
            image_uploaded = Image.create(user_id: user_id, title: title, 
                            image_url: uploaded_image_details['url'], width: uploaded_image_details['width'], 
                            height: uploaded_image_details['height'], format: uploaded_image_details['format'],
                            size_in_bytes: uploaded_image_details['bytes'])
            for tag in tags
                tag = tag.strip
                tag_created  = Tag.create(tag: tag)
                ImageTag.create(image_id: image_uploaded.id, tag_id: tag_created.id)
            end
        end

    end

    class CloudinaryAPI
    
        def upload (image_url)
            return Cloudinary::Uploader.upload(image_url, :type => :private, :sign_url => TRUE)
        end
    end
    
    class SearchImages

        def search (params, user_id)
            tags = params[:image][:tags].split(',')
            image_ids = '';
            for tag in tags
                tag = tag.strip
                tag_found  = Tag.where(tag: "#{tag}")
                if tag_found != nil && tag_found != []
                    image_tag = ImageTag.where(tag_id: tag_found.map{|tag| tag.id})
                    image_ids = image_tag.map{|image| image.image_id}.join('|')
                end
            end
            
            image_for_user =  Image.where(
                "user_id = ? AND 
                id::TEXT similar to ? AND
                title LIKE ? AND 
                width::TEXT LIKE ? AND 
                height::TEXT LIKE ? AND 
                format LIKE ? AND 
                size_in_bytes::TEXT LIKE ?", 
                    user_id,
                    image_ids.blank? ? tags.blank? ? '%': 'null' : image_ids,
                    params[:image][:title].blank? ? '%': params[:image][:title], 
                    params[:image][:width].blank? ? '%': params[:image][:width], 
                    params[:image][:height].blank? ? '%': params[:image][:height],
                    params[:image][:format].blank? ? '%': params[:image][:format],
                    params[:image][:size_in_bytes].blank? ? '%': params[:image][:size_in_bytes]);
            
            return image_for_user
        end

    end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/index.html.erb
<div style="display: inline-block; margin-right: 150px;">
    <b>Upload images</b>
    <%= form_for @image do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :tags %>
        <%= f.text_field :tags %> (add comma separated tag values)
        <%= f.file_field :photo %>
        <%= f.submit :upload%>
    <% end %>
</div>
<br><br>
<div style="display: inline-block">
    <b>Search for images</b>
    <form class="search" id="#{@image.id}" action="/images/show" method="get">
        <label for="title">Title</label>
        <input type="text" name="image[title]" id="image_title">
        <label for="title">Tags</label>
        <input type="text" name="image[tags]" id="image_tags">
        <label for="title">Height</label>
        <input type="text" name="image[height]" id="image_height">
        <label for="title">Width</label>
        <input type="text" name="image[width]" id="image_width">
        <label for="title">Format</label>
        <input type="text" name="image[format]" id="image_format">
        <label for="title">Size in bytes</label>
        <input type="text" name="image[size_in_bytes]" id="image_size">
        <input type="submit" name="commit" value="search">
    </form>    
</div>
<div class="index" style="margin-right: 100px; float: right">
    <%= link_to "Show all images", '/images'%>
</div>
<br> <hr> <br>

<% @image_details.each do |details|%>
    <div class="polaroid">
        <img src="<%= details.image.image_url %>" style="width:100%">
        <div class="container">
            <p><%= details.image.title %> [ <%= details.image.width %> x <%= details.image.height %>]</p>
            <form class="search" id="#{@image.id}" action="/images/similar" method="get">
                <% tags = details.tags.map{|tag_details| tag_details.tag}.join('|') %>
                <input type="hidden" name="imageTags" value="<%=tags%>">
                <input type="hidden" name="imageFormat" value="<%=details.image.format%>">
                <input type="submit" name="Search similar images" value="Search similar images">
            </form>
        </div>
    </div>
<% end%>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picture Uploader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'images.css' %>
  </head>

  <body>
    <% if @logged_in %>
      <div style="display: inline-block; margin-right: 150px; color: #0d98ba">
        Hello, <b><%= @user.username %></b> !!!
      </div>
      <div style="display: inline-block; margin-right: 150px; float: right;">
        <%= button_to "Log out", log_out_path, method: :delete%>
      </div>
      <div class="link">
    <%else%>
      <%= link_to "Log in", new_login_path %> |
      <%= link_to "Sign up", new_user_path %>
    <%end%>
    </div>
    <div>
      <br><br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/new.html.erb
<div class="login">
  <h1 >Log in</h1>
  <%= form_tag login_index_path, class: "auth-form" do %>
    <ul>
      <li>
        <%= label_tag :username %>
        <%= text_field_tag :username %>
      </li>
      <br>
      <li>
        <%= label_tag :password %>
        <%= password_field_tag :password %>
        <% if flash[:message] %>
          <p style="color:red; font-size: 14px;">Password do no not match</p>
        <% end %>
      </li>
    </ul>
    <%= submit_tag "Log in" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="new-user">
  <h1>Create New User</h1>
  <%= form_for @user do |f| %>
    <ul>
      <li>
        <%= f.label :username %>
        <%= f.text_field :username %>
        <% if flash[:errors] && flash[:errors]["username"]%>
          <p style="color:red; font-size: 14px;">Username Already Taken</p>
        <% end %><br />
      </li>
      <br>
      <li>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <br/>
      </li>
    </ul>
    <%= f.submit %>
  <% end %>
</div>